import { Configuration } from '@apttus/core';
export const environment: Configuration = {
  production: false,
  organizationId: '00DL00000061f4D',
  defaultImageSrc: './assets/images/default.png',
  defaultCountry: 'US',
  defaultLanguage: 'en-US',
  enableErrorLogging: false,
  enableErrorReporting: false,
  enableMultiCurrency: false,
  enableQueryLogs: true,
  enablePerformanceLogs: false,
  defaultCurrency: 'USD',
  bufferTime: 50,
  maxBufferSize: 10,
  disableBuffer: false,
  subqueryLimit: 10,
  disableCache: false,
  encryptResponse: false,
  cartRetryLimit: 20,
  productIdentifier: 'Id',
  type: 'Salesforce',
  cartDebounceTime: 2000,
  endpoint: 'https://sum17patch-qawinter18.cs8.force.com/dc',
  proxy: 'https://apttus-proxy.herokuapp.com'
};